version: "3.8"
services:
  api_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8085:8080
    networks:
      - springnet
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/demo1
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0.29"
    restart: always
    ports:
      - 3309:3306
    networks:
      - springnet
    environment:
      MYSQL_DATABASE: demo1
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: 1234
networks:
  springnet: